
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.unisc.project.backend;

import java_cup.runtime.*;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;

import java_cup.runtime.Symbol;

/**
 * CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
 */
@SuppressWarnings({"rawtypes"})
public class ParserPassword extends java_cup.runtime.lr_parser {

    public final Class getSymbolContainer() {
        return Tokens.class;
    }

    /**
     * Default constructor.
     */
    @Deprecated
    public ParserPassword() {
        super();
    }

    /**
     * Constructor which sets the default scanner.
     */
    @Deprecated
    public ParserPassword(java_cup.runtime.Scanner s) {
        super(s);
    }

    /**
     * Constructor which sets the default scanner.
     */
    public ParserPassword(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {
        super(s, sf);
    }

    /**
     * Production table.
     */
    protected static final short _production_table[][] =
            unpackFromStrings(new String[]{
                    "\000\002\000\002\002\002\000\002\002\004"});

    /**
     * Access to production table.
     */
    public short[][] production_table() {
        return _production_table;
    }

    /**
     * Parse-action table.
     */
    protected static final short[][] _action_table =
            unpackFromStrings(new String[]{
                    "\000\003\000\004\002\001\001\002\000\004\002\005\001" +
                            "\002\000\004\002\000\001\002"});

    /**
     * Access to parse-action table.
     */
    public short[][] action_table() {
        return _action_table;
    }

    /**
     * <code>reduce_goto</code> table.
     */
    protected static final short[][] _reduce_table =
            unpackFromStrings(new String[]{
                    "\000\003\000\004\002\003\001\001\000\002\001\001\000" +
                            "\002\001\001"});

    /**
     * Access to <code>reduce_goto</code> table.
     */
    public short[][] reduce_table() {
        return _reduce_table;
    }

    /**
     * Instance of action encapsulation class.
     */
    protected CUP$Parser$actions action_obj;

    /**
     * Action encapsulation object initializer.
     */
    protected void init_actions() {
        action_obj = new CUP$Parser$actions(this);
    }

    /**
     * Invoke a user supplied parse action.
     */
    public java_cup.runtime.Symbol do_action(
            int act_num,
            java_cup.runtime.lr_parser parser,
            java.util.Stack stack,
            int top)
            throws java.lang.Exception {
        /* call code in generated class */
        return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
    }

    /**
     * Indicates start state.
     */
    public int start_state() {
        return 0;
    }

    /**
     * Indicates start production.
     */
    public int start_production() {
        return 1;
    }

    /**
     * <code>EOF</code> Symbol index.
     */
    public int EOF_sym() {
        return 0;
    }

    /**
     * <code>error</code> Symbol index.
     */
    public int error_sym() {
        return 1;
    }


    /**
     * User initialization code.
     */
    public void user_init() throws java.lang.Exception {

    }

    /**
     * Scan to get the next Symbol.
     */
    public java_cup.runtime.Symbol scan()
            throws java.lang.Exception {
        return s.next_token();
    }

    private List<Object> valores = new ArrayList<>();
    private String nome;
    private String sobrenome;
    private String dataNascimento;
    private String setor;

    public void end() {
        System.out.println("Fim do Fluxo!");
    }

    public String getNome(List<Object> o) {
        String name = o.get(0).toString();
        o.remove(0);
        o.remove(0);
        return name;
    }

    public String getSobrenome(List<Object> o) {
        String sobrenome = o.get(0).toString();
        o.remove(0);
        o.remove(0);
        return sobrenome;
    }

    public String getSetor(List<Object> o) {
        String setor = o.get(0).toString();
        o.remove(0);
        o.remove(0);
        return setor;
    }

    public String getDataNascimento(List<Object> o) {
        return o.toString().replace("[", "").replace("]", "");
    }

    private String gerarSenha(String nome, String sobrenome, String setor, String dataNascimentoStr) {
        // Geração de valor aleatório
        String valorAleatorio = gerarValorAleatorio();
        Random random = new Random();

        // Formatar a data de nascimento
        SimpleDateFormat dateFormat = new SimpleDateFormat("ddMMyyyy");
        Date dataNascimento;
        try {
            dataNascimento = dateFormat.parse(dataNascimentoStr.replace("/", ""));
        } catch (Exception e) {
            throw new RuntimeException("Erro ao converter a data de nascimento.", e);
        }

        // Criar variações para a parte inicial da Senha
        String variacao1 = nome.substring(0, 1).toLowerCase() + sobrenome.substring(0, 1).toUpperCase() + sobrenome.toLowerCase();
        String variacao2 = sobrenome.toLowerCase() + nome.substring(0, 1).toUpperCase();
        String variacao3 = setor.substring(0, random.nextInt(0, setor.length())).toUpperCase() + nome.substring(0, 1).toLowerCase();
        String variacao4 = setor.substring(0, random.nextInt(0, setor.length())).toUpperCase() + sobrenome.toLowerCase();
        String variacao5 = nome.toLowerCase() + setor.toLowerCase().substring(0, 1);
        String variacao6 = sobrenome.toLowerCase() + setor.toLowerCase().substring(0, 1);

        // Escolher aleatoriamente uma variação
        int escolhaVariacao = random.nextInt(6); // Escolher aleatoriamente entre as 6 variações

        String variacaoEscolhida;
        switch (escolhaVariacao) {
            case 0:
                variacaoEscolhida = variacao1;
                break;
            case 1:
                variacaoEscolhida = variacao2;
                break;
            case 2:
                variacaoEscolhida = variacao3;
                break;
            case 3:
                variacaoEscolhida = variacao4;
                break;
            case 4:
                variacaoEscolhida = variacao5;
                break;
            case 5:
                variacaoEscolhida = variacao6;
                break;
            default:
                variacaoEscolhida = variacao1;
        }

        // Criar a combinando as informações
        String password = variacaoEscolhida +
                setor.substring(0, 1).toUpperCase() + getSpecialValue() + valorAleatorio
                + dateFormat.format(dataNascimento).toString().substring(random.nextInt(0, 4), random.nextInt(3, 7));

        return password;
    }

    private String getSpecialValue() {
        String values = "[!@#%&*(-_=~`}<>,.?]";
        int pos = values.length();
        Random random = new Random();
        int valor = random.nextInt(random.nextInt(1, pos));
        String special = values.substring(valor, valor + 1);
        return special;
    }

    private String gerarValorAleatorio() {
        // Geração de valor aleatório usando a classe Random
        Random random = new Random();
        int valorAleatorio = random.nextInt(1000); // Valor aleatório entre 0 e 999
        return String.format("%03d", valorAleatorio); // Formatar para garantir três dígitos
    }

    private void salvarValor(List<String> values) {
        try {
            // Cria um objeto FileWriter para escrever no arquivo
            FileWriter fileWriter = new FileWriter("src/main/java/br/com/unisc/project/backend/files/PasswordGenereted");

            // Cria um objeto BufferedWriter para escrever de forma mais eficiente
            BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);

            // Itera sobre a lista e escreve cada string em uma nova linha
            for (String value : values) {
                bufferedWriter.write(value);
                bufferedWriter.newLine(); // Adiciona uma quebra de linha após cada string
            }

            // Fecha os recursos para liberar os recursos do sistema
            bufferedWriter.close();
            fileWriter.close();

            System.out.println("As informações foram salvas no arquivo com sucesso.");

        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    Scanner s;

    ParserPassword(Scanner s) throws java.lang.Exception {
        this.s = s;


        Symbol symbol = s.next_token();
        while (symbol.sym != Tokens.EOF) {
            valores.add(symbol.value);
            System.out.printf("<%d, %s>\n", symbol.sym, symbol.value);
            symbol = s.next_token();
        }

        nome = getNome(valores);
        sobrenome = getSobrenome(valores);
        setor = getSetor(valores);
        dataNascimento = getDataNascimento(valores);

        List<String> passwords = new ArrayList<>();

        for (int i = 0; i < 6; i++) {
            String password = gerarSenha(nome, sobrenome, setor, dataNascimento);
            passwords.add(password);
        }

        salvarValor(passwords);
    }


    /**
     * Cup generated class to encapsulate user supplied action code.
     */
    @SuppressWarnings({"rawtypes", "unchecked", "unused"})
    class CUP$Parser$actions {
        private final ParserPassword parserPassword;

        /**
         * Constructor
         */
        CUP$Parser$actions(ParserPassword parserPassword) {
            this.parserPassword = parserPassword;
        }

        /**
         * Method 0 with the actual generated action code for actions 0 to 300.
         */
        public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
                int CUP$Parser$act_num,
                java_cup.runtime.lr_parser CUP$Parser$parser,
                java.util.Stack CUP$Parser$stack,
                int CUP$Parser$top)
                throws java.lang.Exception {
            /* Symbol object for return from actions */
            java_cup.runtime.Symbol CUP$Parser$result;

            /* select the action based on the action number */
            switch (CUP$Parser$act_num) {
                /*. . . . . . . . . . . . . . . . . . . .*/
                case 0: // fim ::=
                {
                    Object RESULT = null;
                    end();
                    CUP$Parser$result = parserPassword.getSymbolFactory().newSymbol("fim", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                return CUP$Parser$result;

                /*. . . . . . . . . . . . . . . . . . . .*/
                case 1: // $START ::= fim EOF
                {
                    Object RESULT = null;
                    int start_valleft = ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).left;
                    int start_valright = ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).right;
                    Object start_val = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)).value;
                    RESULT = start_val;
                    CUP$Parser$result = parserPassword.getSymbolFactory().newSymbol("$START", 0, ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top - 1)), ((java_cup.runtime.Symbol) CUP$Parser$stack.peek()), RESULT);
                }
                /* ACCEPT */
                CUP$Parser$parser.done_parsing();
                return CUP$Parser$result;

                /* . . . . . .*/
                default:
                    throw new Exception(
                            "Invalid action number " + CUP$Parser$act_num + "found in internal parse table");

            }
        } /* end of method */

        /**
         * Method splitting the generated action code into several parts.
         */
        public final java_cup.runtime.Symbol CUP$Parser$do_action(
                int CUP$Parser$act_num,
                java_cup.runtime.lr_parser CUP$Parser$parser,
                java.util.Stack CUP$Parser$stack,
                int CUP$Parser$top)
                throws java.lang.Exception {
            return CUP$Parser$do_action_part00000000(
                    CUP$Parser$act_num,
                    CUP$Parser$parser,
                    CUP$Parser$stack,
                    CUP$Parser$top);
        }
    }

}
