
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.com.unisc.project.backend;

/** CUP generated class containing symbol constants. */

public class PasswordSym {
  /* terminals */
  public static final int LETTER = 3;
  public static final int DIGIT = 2;
  public static final int SPECIAL = 1;
  public static final int EOF = 0;

  /*public static final String[] terminalNames = new String[] {
          "EOF",
          "LETTER",
          "DIGIT",
          "SPECIAL",
  };*/
}
